[colors.primary]
background = '#282A36'
foreground = '#F8F8F2'

[colors.cursor]
text = '#F8F8F2'
cursor = '#F8F8F2'

[colors.normal]
black   = '#282A36'
red     = '#FF5555'
green   = '#50FA7B'
yellow  = '#F1FA8C'
blue    = '#BD93F9'
magenta = '#FF79C6'
cyan    = '#8BE9FD'
white   = '#F8F8F2'

[colors.bright]
black   = '#282A36'
red     = '#FF5555'
green   = '#50FA7B'
yellow  = '#F1FA8C'
blue    = '#BD93F9'
magenta = '#FF79C6'
cyan    = '#8BE9FD'
white   = '#F8F8F2'